spring.application.name=conta-bancaria-api

springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs